### ISSUE TITLE
add second dataset

### ISSUE THREAD

**Issue by tischi** [BioImageTools/ome-zarr-image-analysis-nextflow#3] opened 2023-11-10 16:29 UTC
@bugraoezdemir could you please also add this data?

https://github.com/NEUBIAS/training-resources/blob/master/image_data/xy_8bit__nuclei_PLK1_inhibition.tif

**Comment by bugraoezdemir** [comment] 2023-11-12 11:53
I have added it to the `develop` branch

**Comment by BioinfoTongLI** [comment] 2023-11-13 11:33
Hi @bugraoezdemir thanks for this!
I am seeing this error:
```
  Traceback (most recent call last):
    File "/lustre/scratch126/cellgen/team283/tl10/ome-zarr-image-analysis-nextflow/bin/blur.py", line 69, in <module>
      main(args)
    File "/lustre/scratch126/cellgen/team283/tl10/ome-zarr-image-analysis-nextflow/bin/blur.py", line 16, in main
      r = Reader(parse_url(args.input, mode="r"))
    File "/usr/local/lib/python3.10/site-packages/ome_zarr/reader.py", line 620, in __init__
      assert zarr.exists()
  AttributeError: 'NoneType' object has no attribute 'exists'
  ```
  and I cannot see the `.zattrs` or `.zgroup`. I assume they are missing?

**Comment by bugraoezdemir** [comment] 2023-11-13 11:47
Hi @BioinfoTongLI , I guess it was because I dragged & dropped the folder and the hidden files were not uploaded. I have fixed it now.

**Comment by BioinfoTongLI** [comment] 2023-11-13 18:57
thanks @bugraoezdemir ! I can confirm it's all good now!
Shall I close this for now? @tischi 
I am also interested in HCS plates. Do you think we should add dummy examples here?

**Closed** 2023-11-14 10:53 UTC
Labels: enhancement
